Coding Simplified Attention

Starting with small embedding vector 

In [3]:
import torch
inputs = torch.tensor([
    [0.43, 0.15, 0.89], # Your (x^1)
    [0.55, 0.87, 0.66], # journey (x^2)
    [0.57, 0.85, 0.64], # starts (x^3)
    [0.22, 0.58, 0.33], # with (x^4)
    [0.77, 0.25, 0.10], # one (x^5)
    [0.05, 0.80, 0.55]  # step (x^6)
])

Step1: Calculate attention scores by dot product with every other vector

In [6]:
query = inputs[1]
attn_scores_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    # A dot product is essentially a concise way of multiplying two vectors element-wise and then summing the products
    attn_scores_2[i] = torch.dot(query, x_i) 
print(attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


Step2: Normalize attention scores to compute attention weights

In [11]:
attn_weights_2_simple = attn_scores_2 / torch.sum(attn_scores_2)
print('Simple: ', attn_weights_2_simple)

# but in general, we want to use the softmax function to convert the attention scores into probabilities, 
# which is more stable and ensures that the weights sum to 1.

attn_weights_2 = torch.softmax(attn_scores_2, dim=0)
print('Softmax: ', attn_weights_2)

Simple:  tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
Softmax:  tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])


Step 3: Calculate the context vector

In [12]:
query = inputs[1]
context_vector_2 = torch.zeros(inputs.shape[1])
for i, x_i in enumerate(inputs):
    context_vector_2 += attn_weights_2[i] * x_i
print('Context vector: ', context_vector_2)

Context vector:  tensor([0.4419, 0.6515, 0.5683])


This entire procedure can be generalized as:

In [24]:
# Step 1: Calculate the attention scores by taking the dot product of the query vector with each of the input vectors.
attn_scores = torch.empty(inputs.shape[0], inputs.shape[0])
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i, j] = torch.dot(x_i, x_j)
print('Calculated by looping:\n', attn_scores)

# We can also calculate the attention scores using matrix multiplication, which is more efficient and concise.
attn_scores_matrix = inputs @ inputs.T
print('Calculated by matrix multiplication:\n', attn_scores_matrix)

# Step 2: Apply the softmax function to the attention scores to get the attention weights.
# By setting dim=-1, you are instructing the softmax function to apply its normalization along the very last dimension of your tensor
attn_weights_matrix = torch.softmax(attn_scores_matrix, dim=1)
print('Attention weights:\n', attn_weights_matrix)

# Step 3: Compute the context vector as a weighted sum of the input vectors, using the attention weights.
context_vector_matrix = attn_weights_matrix @ inputs
print('Context vectors:\n', context_vector_matrix)

Calculated by looping:
 tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])
Calculated by matrix multiplication:
 tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])
Attention weights:
 tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.126